
######################
#Set BASE_DEV_FOLDER
######################

# In Linux VM - JMV i&
#BASE_DEV_FOLDER="/home/jorge/DATOS"

# In Windows WSL - ACN Laptop
#BASE_DEV_FOLDER="/home/jorgemedinavallejo/DEV"

BASE_DEV_FOLDER="/home/jorgemedinavallejo/DEV"

